# -*- coding: utf-8 -*-
"""apppp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2Iy813nk7jV6QshSSaEUShwdTfrf7_N
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import math

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# -------------------------------
# Page Title
# -------------------------------
st.set_page_config(page_title="Insurance Prediction", page_icon="🛡️")

st.title("🛡️ Insurance Purchase Prediction using Logistic Regression")
st.write("Predict whether a person is likely to buy insurance based on age.")

# -------------------------------
# Load Dataset
# -------------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# -------------------------------
# Scatter Plot
# -------------------------------
st.subheader("Age vs Bought Insurance")

fig, ax = plt.subplots()
ax.scatter(df["age"], df["bought_insurance"], marker="+", color="red")
ax.set_xlabel("Age")
ax.set_ylabel("Bought Insurance")
st.pyplot(fig)

# -------------------------------
# Train Model
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    df[["age"]],
    df["bought_insurance"],
    train_size=0.8,
    random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

# -------------------------------
# Model Accuracy
# -------------------------------
accuracy = model.score(X_test, y_test)

st.subheader("Model Accuracy")
st.success(f"Accuracy: {accuracy:.2f}")

# -------------------------------
# Model Parameters
# -------------------------------
st.subheader("Model Parameters")

st.write("Coefficient:", model.coef_)
st.write("Intercept:", model.intercept_)

# -------------------------------
# Predictions on Test Data
# -------------------------------
st.subheader("Predictions on Test Data")

predictions = model.predict(X_test)

result = X_test.copy()
result["Actual"] = y_test.values
result["Predicted"] = predictions

st.dataframe(result)

# -------------------------------
# Sigmoid Function
# -------------------------------
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

def prediction_function(age):
    z = 0.042 * age - 1.53
    return sigmoid(z)

# -------------------------------
# User Input
# -------------------------------
st.subheader("Predict Insurance Purchase")

age = st.slider("Select Age", 18, 70, 35)

probability = prediction_function(age)

st.write(f"Probability: **{probability:.3f}**")

if probability >= 0.5:
    st.success("✅ This person is likely to BUY insurance.")
else:
    st.error("❌ This person is NOT likely to buy insurance.")

# -------------------------------
# Predict using Trained Model
# -------------------------------
st.subheader("Prediction using Trained Model")

model_probability = model.predict_proba([[age]])[0][1]
prediction = model.predict([[age]])[0]

st.write(f"Model Probability: **{model_probability:.3f}**")

if prediction == 1:
    st.success("Prediction: Person will BUY insurance.")
else:
    st.error("Prediction: Person will NOT buy insurance.")
