# -*- coding: utf-8 -*-
"""logistic_regression_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2Iy813nk7jV6QshSSaEUShwdTfrf7_N
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Insurance Purchase Prediction",
    page_icon="🏥",
    layout="centered"
)

st.title("🏥 Insurance Purchase Prediction")
st.write("Predict whether a customer is likely to buy insurance based on their age.")

# -----------------------------
# Load Dataset
# -----------------------------
try:
    df = pd.read_csv("/content/insurance_data.csv")
except FileNotFoundError:
    st.error("❌ insurance_data.csv not found. Please upload it to your GitHub repository.")
    st.stop()

# -----------------------------
# Display Dataset
# -----------------------------
st.subheader("Dataset")
st.dataframe(df)

# -----------------------------
# Prepare Data
# -----------------------------
X = df[["age"]]
y = df["bought_insurance"]

# -----------------------------
# Train Model
# -----------------------------
model = LogisticRegression()
model.fit(X, y)

# -----------------------------
# User Input
# -----------------------------
st.subheader("Enter Customer Details")

age = st.number_input(
    "Age",
    min_value=1,
    max_value=100,
    value=25,
    step=1
)

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict"):

    input_data = pd.DataFrame({"age": [age]})

    prediction = model.predict(input_data)
    probability = model.predict_proba(input_data)[0][1]

    st.subheader("Prediction Result")

    st.write(f"**Probability of Buying Insurance:** {probability*100:.2f}%")

    if prediction[0] == 1:
        st.success("✅ This customer is likely to buy insurance.")
    else:
        st.error("❌ This customer is unlikely to buy insurance.")

# -----------------------------
# Visualization
# -----------------------------
st.subheader("Age vs Bought Insurance")

fig, ax = plt.subplots(figsize=(6,4))
ax.scatter(df["age"], df["bought_insurance"], color="red", marker="+")
ax.set_xlabel("Age")
ax.set_ylabel("Bought Insurance")
ax.set_title("Age vs Bought Insurance")

st.pyplot(fig)